services:
  postgres:
    image: postgres:alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  app:
    image: ghcr.io/shrooq811/skills_utilization:latest
    container_name: skills_app
    ports:
      - "5001:5000"
    environment:
      DB_HOST: postgres
      DB_USER: ${POSTGRES_USER}
      DB_NAME: ${POSTGRES_DB}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres

volumes:
  pgdata:
