name: Deploy Pipeline

on:
  workflow_run:
    workflows: ["Build Pipeline"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy Container Locally
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull and Run Container
        run: |
          docker stop skills_app || true
          docker rm skills_app || true
          docker pull ghcr.io/shrooq811/skills_utilization:latest
          docker run -d --name skills_app -p 5001:5000 ghcr.io/shrooq811/skills_utilization:latest
