name: Deploy Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to Server
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull and Restart Containers via Docker Compose
        run: |
          docker compose pull
          docker compose down
          docker compose up -d
